/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CourseraRouteImport } from './routes/coursera'
import { Route as UdemyRouteImport } from './routes/udemy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CourseraRoute = CourseraRouteImport.update({
  id: '/coursera',
  path: '/coursera',
  getParentRoute: () => rootRouteImport,
} as any)
const UdemyRoute = UdemyRouteImport.update({
  id: '/udemy',
  path: '/udemy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/coursera': typeof CourseraRoute
  '/udemy': typeof UdemyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/coursera': typeof CourseraRoute
  '/udemy': typeof UdemyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/coursera': typeof CourseraRoute
  '/udemy': typeof UdemyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/coursera' | '/udemy'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/coursera' | '/udemy'
  id: '__root__' | '/' | '/coursera' | '/udemy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CourseraRoute: typeof CourseraRoute
  UdemyRoute: typeof UdemyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coursera': {
      id: '/coursera'
      path: '/coursera'
      fullPath: '/coursera'
      preLoaderRoute: typeof CourseraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/udemy': {
      id: '/udemy'
      path: '/udemy'
      fullPath: '/udemy'
      preLoaderRoute: typeof UdemyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CourseraRoute: CourseraRoute,
  UdemyRoute: UdemyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
